apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: static-nginx
spec:
  containers:
  - name: static-nginx
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    ports:
      - containerPort: 80
