apiVersion: v1
kind: Pod
metadata:
  name: nodejs-web-server
spec:
  containers:
  - name: nodejs
    image: node:14
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["node", "-e"]
    args: ["const http = require('http'); const server = http.createServer((req, res) => { res.end('Hello, World!'); }); server.listen(3000);"]
    ports:
    - containerPort: 3000
    readinessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 10