apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  initContainers:
  - name: init-busybox
    image: busybox
    command: ['sh', '-c', 'sleep 20']
  containers:
  - name: redis
    image: redis
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"