apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
spec:
  ports:
    - name: port-backend
      port: 8080
      targetPort: 8080
  selector:
    run: ingress-default-backend
