apiVersion: v1
kind: Pod
metadata:
  name: volume-share-datacenter
spec:
  containers:
    - name: volume-container-datacenter-1
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/news
    # ------------------------------ SECOND CONTAINER :
    - name: volume-container-datacenter-2
      image: centos:latest
      command: ["/bin/bash", "-c", "sleep 10000"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: volume-share
          mountPath: /tmp/cluster
  volumes:
    - name: volume-share
      emptyDir: {}
