apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    tier: front-end
    environment: production
spec:
  volumes:
    - name: emptydir-volume
      emptyDir: {}
    - name: nfs-volume
      nfs:
        server: 192.168.1.12
        path: /mnt/shared
  containers:
    - name: main-container
      image: nginx:alpine
      resources:
        requests:
          memory: "128M"
          cpu: "200m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        # - name: nfs-volume
        # mountPath: /mnt/nfs
        - name: emptydir-volume
          mountPath: /mnt/shared
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 4
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
    - name: sidecar-container
      image: busybox
      resources:
        requests:
          memory: "16Mi"
          cpu: "100m"
        limits:
          memory: "32Mi"
          cpu: "200m"
      volumeMounts:
        # - name: nfs-volume
        # mountPath: /mnt/nfs
        - name: emptydir-volume
          mountPath: /mnt/shared
      command:
        [
          "/bin/sh",
          "-c",
          "while true; do echo $(date)  '- Side Car logging' ; sleep 5 ; done",
        ]
